[feat] github webhook body parsing logic implemented
cqbqdd11519/cicd-operator pull request #16
Opened 2020-11-20 05:00 UTC by kyung-hoon

2020-11-20 05:29 UTC, cqbqdd11519 requested changes
웹훅 바디를 이용해서  https://github.com/cqbqdd11519/cicd-operator/blob/master/docs/integrationJob.md 의 `spec.refs`를 만들 수 있도록 필드 몇개 추가 부탁드려요~

2020-11-20 05:29 UTC, cqbqdd11519 commented on pkg/git/webhook_types.go
>  type PullRequest struct {
PullRequest 웹훅에는 base / head 별 sha와 ref, link가 필요할 것 같습니다

2020-11-20 05:29 UTC, cqbqdd11519 commented on pkg/git/webhook_types.go
>  type Push struct {
Push 웹훅에는 sha가 필요합니다
Github 웹훅 payload 보니까 코드 push일 경우 `after`가 sha에 들어가면 될 것 같고 tag push일 경우 (ref가 refs/tags/~~ 일 경우) `before`가 여기 들어가면 될 것 같습니다

2020-11-20 05:29 UTC, cqbqdd11519 commented on pkg/git/webhook_types.go
>  type PullRequest struct {
pull request id(number)도 필요할 것 같습니다

2020-11-20 05:29 UTC, cqbqdd11519 commented on pkg/git/webhook_types.go
> +	Sender string
Sender는 name/link가 저장돼야 할 것 같습니다

2020-11-20 05:38 UTC, kyung-hoon commented on pkg/git/webhook_types.go
>  type PullRequest struct {
넵 리뷰 다 확인하고 수정해서 다시 올리겠습니다~

2020-11-20 05:55 UTC, kyung-hoon commented on pkg/git/webhook_types.go
>  type PullRequest struct {
여기 말씀하시는 link가 정확히 어떤걸 의미하는건 지 알수 잇을까요?

2020-11-20 05:59 UTC, cqbqdd11519 commented on pkg/git/webhook_types.go
>  type PullRequest struct {
아 link는 base/head별로 구분할 필요가 없겠네요
지금 Url 변수로 충분할것같습니다

2020-11-23 01:13 UTC, cqbqdd11519 approved these changes

2020-11-23 01:30 UTC, cqbqdd11519 commented
머지할때는 Squash and merge로 부탁드려요ㅎㅎ

2020-11-23 05:10 UTC, yshcoffee commented on pkg/git/github/github.go
>  }
error가 발생했을 때 error 반환하는 로직이 추가되면 좋을 거 같습니다

2020-11-23 05:13 UTC, JINwonLEE commented on pkg/git/github/github.go
> +	if eventType == "pull_request" {
Event type같은 경우에 따로 type으로 상수화 해놓는게 더 보기 좋을 거 같습니다.

2020-11-23 06:38 UTC, kyung-hoon commented on pkg/git/github/github.go
>  }
수정 완료했습니다.

2020-11-23 06:38 UTC, kyung-hoon commented on pkg/git/github/github.go
> +	if eventType == "pull_request" {
수정완료했습니다.

2020-11-23 06:41 UTC, cqbqdd11519 commented on pkg/git/github/github.go
> +		}
`err`가 nil일 경우 아래처럼 바로 err를 return하는게 좋지 않을까 싶어요
```go
if err := json.Unamrshal(jsonString, &data); err != nil {
  return return git.Webhook{}, err
}
sender := ....
```

2020-11-23 06:48 UTC, yshcoffee commented on pkg/git/github/github.go
> +	var eventType = git.EventType(header.Get("X-Github-Event"))
"X-Github-Event"의 값으로 pull_request, push 이 두가지 이외의 값은 없는건가요?

2020-11-23 07:04 UTC, cqbqdd11519 commented on pkg/git/github/github.go
> +	return webhook, err
X-Github-Event 가 push/pull_request 말고 다른 값이 들어올 수도 있으니까 여기 else 따서
```go
return git.Webhook{}, fmt.Errorf("event %s is not supported")
```
같이 아직 지원되지 않는 이벤트가 들어오면 error 뱉어주는게 좋을것 같아요

2020-11-23 07:12 UTC, cqbqdd11519 commented on pkg/git/github/github.go
> +	return webhook, err
요거는 내키시면 하시고 안하셔도 상관은 없을것 같아요ㅎㅎ

나중에 GitHub/GitLab용 webhook validation 함수 따로 추가해서 거기에 넣어도 될 것 같네요

2020-11-23 07:16 UTC, cqbqdd11519 approved these changes

2020-11-23 07:23 UTC, kyung-hoon commented on pkg/git/github/github.go
> +	return webhook, err
일단은 추가했습니다. 나중에 근데 validation을 만드는 방법이 더 좋긴할거 같네요

2020-11-23 07:23 UTC, kyung-hoon commented on pkg/git/github/github.go
> +		}
수정완료.

2020-11-23 09:40 UTC, yshcoffee approved these changes

2020-11-24 00:35 UTC, cqbqdd11519 approved these changes

2020-11-24 08:07 UTC, kyung-hoon commented
@JINwonLEE 리뷰 완료 되시면 squash and merge 부탁드려요.

2020-11-25 06:08 UTC, merged